apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lensfinder
resources:
  - namespace.yaml
  - postgres.yaml
  - server.yaml
  - client.yaml
  - ingress.yaml
  - redis.yaml
  - server-monitor.yaml
