apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  CACHE_TTL_S: "300"
  REDIS_URL: "redis://redis:6379/0"
  # Security and API headers
  SIGNATURE_TTL_SECONDS: "300"
  SIGNATURE_EXCLUDE_PATHS: "/graphql,/api/health"
  API_VERSION_CURRENT: "v1"
  API_VERSION_DEPRECATED: ""
  API_VERSION_POLICY_URL: ""
  # CORS and proxy
  CORS_ALLOWED_ORIGINS: ""
  TRUST_PROXY: "true"
  # Limits
  RATE_LIMIT_GLOBAL_PER_MIN: "600"
  RATE_LIMIT_PRICE_PER_MIN: "60"
  JSON_BODY_LIMIT: "256kb"
  # Logging
  LOG_LEVEL: "info"
  # CORS and proxy
  CORS_ALLOWED_ORIGINS: ""
  TRUST_PROXY: "true"
  # Rate limits and body size
  RATE_LIMIT_GLOBAL_PER_MIN: "600"
  RATE_LIMIT_PRICE_PER_MIN: "60"
  JSON_BODY_LIMIT: "256kb"
  # API versioning
  API_VERSION_CURRENT: "v1"
  API_VERSION_DEPRECATED: ""
  API_VERSION_POLICY_URL: ""
  # Signature middleware
  SIGNATURE_EXCLUDE_PATHS: "/graphql,/api/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://lens:lens@postgres:5432/lensfinder"
  REQUEST_SIGNATURE_SECRET: ""
  API_KEY: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: lensfinder-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secret
          ports:
            - name: http
              containerPort: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 3001
      targetPort: 3001
