/*
  Merge and normalize new lens entries into server/data/lenses.json and data/lenses.json.
  - Maps mounts to short codes used by the app
  - Ensures required fields exist (brand, is_macro, distortion_pct, focus_breathing_score, source_url)
  - Splits multi-mount entries into separate items
  - Deduplicates by name+mount, preferring new data
*/

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

// Paste of user-provided lenses
const provided = [
  {"name":"Canon RF 85mm F1.2 L USM","lens_type":"Prime","mount":"Canon RF","coverage":"FF","focal_min_mm":85,"focal_max_mm":85,"aperture_min":1.2,"aperture_max":16,"min_f_number":16,"diaphragm_blades":9,"filter_thread_mm":82,"elements_count":13,"groups_count":9,"min_focus_distance_mm":850,"max_magnification":0.12,"focus_motor":"Ring USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1195,"length_mm":117.3,"diameter_mm":103.2,"ois":false,"price_chf":3199,"price_usd":2999,"price_eur":3099,"notes":"Flagship portrait prime with exceptional sharpness and bokeh.","sources":["https://www.canon-europe.com/lenses/rf-85mm-f1-2l-usm/","https://www.lenstip.com/569.1-Lens_review-Canon_RF_85_mm_f_1.2L_USM_Introduction.html","https://www.foto-erhardt.de/objektive/canon/canon-rf-85mm-f-1-2l-usm.html"]},
  {"name":"Canon RF 100-500mm F4.5-7.1 L IS USM","lens_type":"Zoom","mount":"Canon RF","coverage":"FF","focal_min_mm":100,"focal_max_mm":500,"aperture_min":4.5,"aperture_max":7.1,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":77,"elements_count":20,"groups_count":14,"min_focus_distance_mm":900,"max_magnification":0.33,"focus_motor":"Dual Nano USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1530,"length_mm":207.6,"diameter_mm":93.8,"ois":true,"price_chf":3499,"price_usd":2899,"price_eur":2999,"notes":"Versatile super tele zoom with strong stabilization.","sources":["https://www.canon-europe.com/lenses/rf-100-500mm-f4-5-7-1-l-is-usm/","https://www.dpreview.com/reviews/canon-rf-100-500mm-f4-5-7-1-l-is-usm-review","https://www.digitec.ch/en/s1/product/canon-rf-100-500mm-f45-71-l-is-usm-canon-rf-cameras-lens-13258289"]},
  {"name":"Canon RF-S 18-150mm F3.5-6.3 IS STM","lens_type":"Zoom","mount":"Canon RF-S","coverage":"APS-C","focal_min_mm":18,"focal_max_mm":150,"aperture_min":3.5,"aperture_max":6.3,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":55,"elements_count":17,"groups_count":13,"min_focus_distance_mm":170,"max_magnification":0.44,"focus_motor":"STM","autofocus":true,"weather_sealed":false,"country_of_origin":"Taiwan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":310,"length_mm":84.5,"diameter_mm":69,"ois":true,"price_chf":599,"price_usd":499,"price_eur":539,"notes":"Lightweight all-in-one zoom for Canon APS-C RF bodies.","sources":["https://www.canon-europe.com/lenses/rf-s-18-150mm-f3-5-6-3-is-stm/","https://www.dpreview.com/products/canon/lenses/canon_rf-s_18-150_3p5-6p3_is_stm","https://www.foto-erhardt.de/objektive/canon/canon-rf-s-18-150mm-f-3-5-6-3-is-stm.html"]},
  {"name":"Canon RF 35mm F1.8 Macro IS STM","lens_type":"Prime","mount":"Canon RF","coverage":"FF","focal_min_mm":35,"focal_max_mm":35,"aperture_min":1.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":52,"elements_count":11,"groups_count":9,"min_focus_distance_mm":170,"max_magnification":0.5,"focus_motor":"STM","autofocus":true,"weather_sealed":false,"country_of_origin":"Taiwan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":305,"length_mm":62.8,"diameter_mm":74.4,"ois":true,"price_chf":529,"price_usd":499,"price_eur":555,"notes":"Compact macro wide prime, affordable but sharp.","sources":["https://www.canon-europe.com/lenses/rf-35mm-f1-8-macro-is-stm/","https://www.lenstip.com/562.1-Lens_review-Canon_RF_35_mm_f_1.8_Macro_IS_STM_Introduction.html","https://www.digitec.ch/en/s1/product/canon-rf-35mm-f18-macro-is-stm-canon-rf-cameras-lens-9730986"]},
  {"name":"Canon RF 16mm F2.8 STM","lens_type":"Prime","mount":"Canon RF","coverage":"FF","focal_min_mm":16,"focal_max_mm":16,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":43,"elements_count":9,"groups_count":7,"min_focus_distance_mm":130,"max_magnification":0.25,"focus_motor":"STM","autofocus":true,"weather_sealed":false,"country_of_origin":"Taiwan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":165,"length_mm":40,"diameter_mm":69.2,"ois":false,"price_chf":349,"price_usd":299,"price_eur":325,"notes":"Affordable lightweight ultra-wide, fast, good for video/vlog.","sources":["https://www.canon-europe.com/lenses/rf-16mm-f2-8-stm/","https://www.photoreview.com.au/reviews/lenses/canon-rf-16mm-f2-8-stm-lens/","https://www.digitec.ch/en/s1/product/canon-rf-16mm-f28-stm-canon-rf-cameras-lens-17187053"]},
  {"name":"Canon EF 24-70mm F2.8L II USM","lens_type":"Zoom","mount":"Canon EF","coverage":"FF","focal_min_mm":24,"focal_max_mm":70,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":82,"elements_count":18,"groups_count":13,"min_focus_distance_mm":380,"max_magnification":0.21,"focus_motor":"Ring USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":800,"length_mm":113,"diameter_mm":88.5,"ois":false,"price_chf":1849,"price_usd":1899,"price_eur":1949,"notes":"Classic pro standard zoom for DSLRs; robust and sharp.","sources":["https://www.canon-europe.com/lenses/ef-24-70mm-f2-8l-ii-usm/","https://www.lenstip.com/351.1-Lens_review-Canon_EF_24-70_mm_f_2.8_L_II_USM_Introduction.html","https://www.digitec.ch/en/s1/product/canon-ef-24-70mm-f28-l-ii-usm-canon-ef-cameras-lens-325100"]},
  {"name":"Canon EF 70-200mm F2.8L IS III USM","lens_type":"Zoom","mount":"Canon EF","coverage":"FF","focal_min_mm":70,"focal_max_mm":200,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":32,"diaphragm_blades":8,"filter_thread_mm":77,"elements_count":23,"groups_count":19,"min_focus_distance_mm":1200,"max_magnification":0.21,"focus_motor":"Ring USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1480,"length_mm":199,"diameter_mm":88.8,"ois":true,"price_chf":2399,"price_usd":2099,"price_eur":2249,"notes":"Legendary EF telephoto zoom with IS and pro build.","sources":["https://www.canon-europe.com/lenses/ef-70-200mm-f-2-8l-is-iii-usm/","https://www.dpreview.com/news/6481780110/canon-announces-ef-70-200mm-f2-8l-is-iii-usm-lens","https://www.digitec.ch/en/s1/product/canon-ef-70-200mm-f28l-is-iii-usm-canon-ef-cameras-lens-9182324"]},
  {"name":"Canon EF 100mm F2.8L Macro IS USM","lens_type":"Prime","mount":"Canon EF","coverage":"FF","focal_min_mm":100,"focal_max_mm":100,"aperture_min":2.8,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":67,"elements_count":15,"groups_count":12,"min_focus_distance_mm":300,"max_magnification":1.0,"focus_motor":"USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":625,"length_mm":123,"diameter_mm":77.7,"ois":true,"price_chf":1189,"price_usd":1299,"price_eur":1149,"notes":"Highly regarded L-series macro with hybrid IS.","sources":["https://www.canon-europe.com/lenses/ef-100mm-f-2-8l-macro-is-usm/","https://www.lenstip.com/229.1-Lens_review-Canon_EF_100_mm_f_2.8_L_Macro_IS_USM_Introduction.html","https://www.foto-erhardt.de/objektive/canon/canon-ef-100mm-f-28l-macro-is-usm.html"]},
  {"name":"Canon EF 8-15mm F4L Fisheye USM","lens_type":"Zoom","mount":"Canon EF","coverage":"FF","focal_min_mm":8,"focal_max_mm":15,"aperture_min":4.0,"aperture_max":22,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":null,"elements_count":14,"groups_count":11,"min_focus_distance_mm":150,"max_magnification":0.34,"focus_motor":"Ring USM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":540,"length_mm":83,"diameter_mm":78.5,"ois":false,"price_chf":1439,"price_usd":1249,"price_eur":1299,"notes":"Unique zoom fisheye lens for full-frame and APS-C bodies.","sources":["https://www.canon-europe.com/lenses/ef-8-15mm-f-4l-fisheye-usm/","https://www.lenstip.com/281.1-Lens_review-Canon_EF_8-15_mm_f_4L_Fisheye_USM_Introduction.html","https://www.digitec.ch/en/s1/product/canon-ef-8-15mm-f4l-fisheye-usm-canon-ef-cameras-lens-325157"]},
  {"name":"Nikon Z 24-70mm F2.8 S","lens_type":"Zoom","mount":"Nikon Z","coverage":"FF","focal_min_mm":24,"focal_max_mm":70,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":82,"elements_count":17,"groups_count":15,"min_focus_distance_mm":380,"max_magnification":0.22,"focus_motor":"Multi-Focus System","autofocus":true,"weather_sealed":true,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":805,"length_mm":126,"diameter_mm":89,"ois":false,"price_chf":2399,"price_usd":1899,"price_eur":1949,"notes":"Professional standard zoom lens for Z cameras.","sources":["https://www.nikon.ch/en_CH/product/nikkor-z-lenses/mirrorless/zoom/nikkor-z-24-70mm-f-2-8-s","https://www.dpreview.com/reviews/nikon-z-24-70mm-f2-8-s-review","https://www.digitec.ch/en/s1/product/nikon-nikkor-z-24-70mm-f28-s-nikon-z-cameras-lens-11563912"]},
  {"name":"Nikon Z 70-200mm F2.8 VR S","lens_type":"Zoom","mount":"Nikon Z","coverage":"FF","focal_min_mm":70,"focal_max_mm":200,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":77,"elements_count":21,"groups_count":18,"min_focus_distance_mm":500,"max_magnification":0.2,"focus_motor":"STM & Voice Coil AM","autofocus":true,"weather_sealed":true,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1360,"length_mm":220,"diameter_mm":89,"ois":true,"price_chf":2899,"price_usd":2599,"price_eur":2649,"notes":"Premium telephoto Z-mount zoom with VR and pro build.","sources":["https://www.nikon.ch/en_CH/product/nikkor-z-lenses/mirrorless/zoom/nikkor-z-70-200mm-f-2-8-vr-s","https://www.lenstip.com/564.1-Lens_review-Nikon_Nikkor_Z_70-200_mm_f_2.8_VR_S_Introduction.html","https://www.foto-erhardt.de/objektive/nikon/nikon-z-70-200mm-f-2-8-vr-s.html"]},
  {"name":"Nikon Z MC 105mm F2.8 VR S","lens_type":"Prime","mount":"Nikon Z","coverage":"FF","focal_min_mm":105,"focal_max_mm":105,"aperture_min":2.8,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":62,"elements_count":16,"groups_count":11,"min_focus_distance_mm":294,"max_magnification":1.0,"focus_motor":"STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":630,"length_mm":140,"diameter_mm":82,"ois":true,"price_chf":999,"price_usd":1049,"price_eur":1059,"notes":"Macro S-Line lens, 1:1, with VR and robust sealing.","sources":["https://www.nikon.ch/en_CH/product/nikkor-z-lenses/mirrorless/prime/nikkor-z-mc-105mm-f-2-8-vr-s","https://www.dpreview.com/reviews/nikon-z-mc-105mm-f2-8-vr-s-sample-gallery","https://www.digitec.ch/en/s1/product/nikon-nikkor-z-mc-105mm-f28-vr-s-nikon-z-cameras-lens-16890586"]},
  {"name":"Nikon Z 85mm F1.2 S","lens_type":"Prime","mount":"Nikon Z","coverage":"FF","focal_min_mm":85,"focal_max_mm":85,"aperture_min":1.2,"aperture_max":16,"min_f_number":16,"diaphragm_blades":11,"filter_thread_mm":82,"elements_count":15,"groups_count":10,"min_focus_distance_mm":850,"max_magnification":0.12,"focus_motor":"STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1160,"length_mm":141,"diameter_mm":98.5,"ois":false,"price_chf":3299,"price_usd":2999,"price_eur":3199,"notes":"Flagship Z portrait prime — outstanding bokeh and build.","sources":["https://www.nikon.ch/en_CH/product/nikkor-z-lenses/mirrorless/prime/nikkor-z-85mm-f-1-2-s","https://www.lenstip.com/668.1-Lens_review-Nikon_Nikkor_Z_85_mm_f_1.2_S_Introduction.html","https://www.foto-erhardt.de/objektive/nikon/nikon-z-85mm-f-1-2-s.html"]},
  {"name":"Nikon Z 400mm F2.8 TC VR S","lens_type":"Prime","mount":"Nikon Z","coverage":"FF","focal_min_mm":400,"focal_max_mm":400,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":null,"elements_count":25,"groups_count":19,"min_focus_distance_mm":2500,"max_magnification":0.16,"focus_motor":"STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":2950,"length_mm":380,"diameter_mm":156,"ois":true,"price_chf":14999,"price_usd":13999,"price_eur":14499,"notes":"Super telephoto prime with built-in 1.4× teleconverter.","sources":["https://www.nikonusa.com/en/nikon-products/product/nikkor-z-lenses/nikkor-z-400mm-f28-tc-vr-s.html","https://www.dpreview.com/news/7822247513/nikon-unveils-400mm-f2-8-vr-s-lens-with-built-in-teleconverter","https://www.foto-erhardt.de/objektive/nikon/nikon-z-400mm-f-28-tc-vr-s.html"]},
  {"name":"Nikon Z 800mm F6.3 VR S","lens_type":"Prime","mount":"Nikon Z","coverage":"FF","focal_min_mm":800,"focal_max_mm":800,"aperture_min":6.3,"aperture_max":6.3,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":null,"elements_count":22,"groups_count":14,"min_focus_distance_mm":5000,"max_magnification":0.16,"focus_motor":"STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":2385,"length_mm":385,"diameter_mm":140,"ois":true,"price_chf":7799,"price_usd":6499,"price_eur":7199,"notes":"Lightweight PF super telephoto prime for Z-mount.","sources":["https://www.nikonusa.com/en/nikon-products/product/nikkor-z-lenses/nikkor-z-800mm-f63-vr-s.html","https://www.dpreview.com/news/5357419946/nikon-announces-lightweight-800mm-f6-3-vr-s-super-telephoto-lens","https://www.digitec.ch/en/s1/product/nikon-nikkor-z-800mm-f63-vr-s-nikon-z-cameras-lens-19222849"]},
  {"name":"Nikon PC-E 19mm F4E ED","lens_type":"Prime","mount":"Nikon F","coverage":"FF","focal_min_mm":19,"focal_max_mm":19,"aperture_min":4.0,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":null,"elements_count":17,"groups_count":13,"min_focus_distance_mm":250,"max_magnification":0.18,"focus_motor":"Manual Focus","autofocus":false,"weather_sealed":false,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":885,"length_mm":124,"diameter_mm":89,"ois":false,"price_chf":3799,"price_usd":3399,"price_eur":3499,"notes":"Perspective Control tilt-shift wide-angle lens.","sources":["https://www.nikonusa.com/en/nikon-products/product/camera-lenses/pc-nikkor-19mm-f%252f4e-ed.html","https://www.imaging-resource.com/lenses/nikon/19mm-f4e-pc-e-ed/review/","https://www.foto-koester.de/nikon-pc-e-nikkor-19mm-14e-ed.html"]},
  {"name":"Nikon Z 14-24mm F2.8 S","lens_type":"Zoom","mount":"Nikon Z","coverage":"FF","focal_min_mm":14,"focal_max_mm":24,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":112,"elements_count":16,"groups_count":11,"min_focus_distance_mm":280,"max_magnification":0.13,"focus_motor":"STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":650,"length_mm":124.5,"diameter_mm":89,"ois":false,"price_chf":2499,"price_usd":2399,"price_eur":2449,"notes":"Ultra-wide pro zoom for Z; excellent sharpness and flare control.","sources":["https://www.nikon.ch/en_CH/product/nikkor-z-lenses/mirrorless/zoom/nikkor-z-14-24mm-f-2-8-s","https://www.lenstip.com/595.1-Lens_review-Nikon_Nikkor_Z_14-24_mm_f_2.8_S_Introduction.html","https://www.foto-erhardt.de/objektive/nikon/nikon-z-14-24mm-f-2-8-s.html"]},
  {"name":"Nikon Z DX 16-50mm F3.5-6.3 VR","lens_type":"Zoom","mount":"Nikon Z","coverage":"APS-C","focal_min_mm":16,"focal_max_mm":50,"aperture_min":3.5,"aperture_max":6.3,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":46,"elements_count":9,"groups_count":7,"min_focus_distance_mm":200,"max_magnification":0.2,"focus_motor":"STM","autofocus":true,"weather_sealed":false,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":135,"length_mm":32,"diameter_mm":70,"ois":true,"price_chf":299,"price_usd":299,"price_eur":319,"notes":"Entry-level DX kit zoom for Z APS-C bodies.","sources":["https://www.nikonusa.com/en/nikon-products/product/nikkor-z-lenses/nikkor-z-dx-16-50mm-f3-5-6-3-vr.html","https://www.photoreview.com.au/reviews/lenses/nikon-z-dx-16-50mm-f3-5-6-3-vr/","https://www.digitec.ch/en/s1/product/nikon-nikkor-z-dx-16-50mm-f35-63-vr-nikon-z-cameras-lens-14074316"]},
  {"name":"Nikon AF-S 200-500mm F5.6E ED VR","lens_type":"Zoom","mount":"Nikon F","coverage":"FF","focal_min_mm":200,"focal_max_mm":500,"aperture_min":5.6,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":95,"elements_count":19,"groups_count":12,"min_focus_distance_mm":2200,"max_magnification":0.22,"focus_motor":"Ring SWM","autofocus":true,"weather_sealed":false,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":2300,"length_mm":267.5,"diameter_mm":108,"ois":true,"price_chf":1599,"price_usd":1399,"price_eur":1499,"notes":"Affordable supertele zoom, popular wildlife choice.","sources":["https://www.nikon.ch/en_CH/product/camera-lenses/af-s-nikkor-200-500mm-f-5.6e-ed-vr","https://www.lenstip.com/443.1-Lens_review-Nikon_Nikkor_AF-S_200-500_mm_f_5.6E_ED_VR_Introduction.html","https://www.foto-erhardt.de/objektive/nikon/nikon-af-s-nikkor-200-500mm-f-5-6e-ed-vr.html"]},
  {"name":"Sony FE 24-70mm F2.8 GM II","lens_type":"Zoom","mount":"Sony E","coverage":"FF","focal_min_mm":24,"focal_max_mm":70,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":82,"elements_count":20,"groups_count":15,"min_focus_distance_mm":210,"max_magnification":0.32,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":695,"length_mm":120,"diameter_mm":87.8,"ois":false,"price_chf":2399,"price_usd":2299,"price_eur":2399,"notes":"Second-generation G Master standard zoom, lighter and sharper.","sources":["https://www.sony.com/electronics/camera-lenses/sel2470gm2","https://www.dpreview.com/reviews/sony-fe-24-70mm-f2-8-gm-ii-review","https://www.digitec.ch/en/s1/product/sony-fe-24-70mm-f28-gm-ii-sony-e-cameras-lens-21240786"]},
  {"name":"Sony FE 70-200mm F2.8 GM OSS II","lens_type":"Zoom","mount":"Sony E","coverage":"FF","focal_min_mm":70,"focal_max_mm":200,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":77,"elements_count":17,"groups_count":14,"min_focus_distance_mm":400,"max_magnification":0.3,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1045,"length_mm":200,"diameter_mm":88,"ois":true,"price_chf":2899,"price_usd":2799,"price_eur":2849,"notes":"Redesigned G Master telephoto zoom, significantly lighter than predecessor.","sources":["https://www.sony.com/electronics/camera-lenses/sel70200gm2","https://www.lenstip.com/631.1-Lens_review-Sony_FE_70-200_mm_f_2.8_GM_OSS_II_Introduction.html","https://www.foto-erhardt.de/objektive/sony/sony-fe-70-200mm-f-2-8-gm-oss-ii.html"]},
  {"name":"Sony FE 35mm F1.4 GM","lens_type":"Prime","mount":"Sony E","coverage":"FF","focal_min_mm":35,"focal_max_mm":35,"aperture_min":1.4,"aperture_max":16,"min_f_number":16,"diaphragm_blades":11,"filter_thread_mm":67,"elements_count":14,"groups_count":10,"min_focus_distance_mm":250,"max_magnification":0.26,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":524,"length_mm":96,"diameter_mm":76,"ois":false,"price_chf":1649,"price_usd":1499,"price_eur":1599,"notes":"High-end G Master wide prime lens, excellent low-light and bokeh.","sources":["https://www.sony.com/electronics/camera-lenses/sel35f14gm","https://www.dpreview.com/reviews/sony-fe-35mm-f1-4-gm-review","https://www.digitec.ch/en/s1/product/sony-fe-35mm-f14-gm-sony-e-cameras-lens-14825737"]},
  {"name":"Sony FE 85mm F1.4 GM","lens_type":"Prime","mount":"Sony E","coverage":"FF","focal_min_mm":85,"focal_max_mm":85,"aperture_min":1.4,"aperture_max":16,"min_f_number":16,"diaphragm_blades":11,"filter_thread_mm":77,"elements_count":11,"groups_count":8,"min_focus_distance_mm":800,"max_magnification":0.12,"focus_motor":"Ring SSM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":820,"length_mm":107.5,"diameter_mm":89.5,"ois":false,"price_chf":1699,"price_usd":1799,"price_eur":1749,"notes":"Flagship portrait prime in the G Master series.","sources":["https://www.sony.com/electronics/camera-lenses/sel85f14gm","https://www.lenstip.com/482.1-Lens_review-Sony_FE_85_mm_f_1.4_GM_Introduction.html","https://www.foto-erhardt.de/objektive/sony/sony-fe-85mm-f-1-4-gm.html"]},
  {"name":"Sony FE 90mm F2.8 Macro G OSS","lens_type":"Prime","mount":"Sony E","coverage":"FF","focal_min_mm":90,"focal_max_mm":90,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":62,"elements_count":15,"groups_count":11,"min_focus_distance_mm":279,"max_magnification":1.0,"focus_motor":"Direct Drive SSM","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":602,"length_mm":130.5,"diameter_mm":79,"ois":true,"price_chf":1049,"price_usd":1099,"price_eur":1099,"notes":"Pro macro with 1:1 reproduction, OSS stabilization.","sources":["https://www.sony.com/electronics/camera-lenses/sel90m28g","https://www.imaging-resource.com/lenses/sony/fe-90mm-f2.8-macro-g-oss/review/","https://www.digitec.ch/en/s1/product/sony-fe-90mm-f28-macro-g-oss-sony-e-cameras-lens-3532311"]},
  {"name":"Sony FE 50mm F1.2 GM","lens_type":"Prime","mount":"Sony E","coverage":"FF","focal_min_mm":50,"focal_max_mm":50,"aperture_min":1.2,"aperture_max":16,"min_f_number":16,"diaphragm_blades":11,"filter_thread_mm":72,"elements_count":14,"groups_count":10,"min_focus_distance_mm":400,"max_magnification":0.17,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":778,"length_mm":108,"diameter_mm":87,"ois":false,"price_chf":2299,"price_usd":1999,"price_eur":2099,"notes":"Ultra-fast standard prime for Sony E; superb optical quality.","sources":["https://www.sony.com/electronics/camera-lenses/sel50f12gm","https://www.dpreview.com/news/5584864073/sony-announces-fe-50mm-f1-2-g-master-lens-for-full-frame-e-mount","https://www.foto-erhardt.de/objektive/sony/sony-fe-50mm-f-1-2-gm.html"]},
  {"name":"Sony FE 14mm F1.8 GM","lens_type":"Prime","mount":"Sony E","coverage":"FF","focal_min_mm":14,"focal_max_mm":14,"aperture_min":1.8,"aperture_max":16,"min_f_number":16,"diaphragm_blades":9,"filter_thread_mm":null,"elements_count":14,"groups_count":11,"min_focus_distance_mm":250,"max_magnification":0.1,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":460,"length_mm":99.8,"diameter_mm":83,"ois":false,"price_chf":1699,"price_usd":1599,"price_eur":1649,"notes":"Ultra‑wide-angle G Master prime, ideal for astro and landscapes.","sources":["https://www.sony.com/electronics/camera-lenses/sel14f18gm","https://www.lenstip.com/614.1-Lens_review-Sony_FE_14_mm_f_1.8_GM_Introduction.html","https://www.foto-erhardt.de/objektive/sony/sony-fe-14mm-f-1-8-gm.html"]},
  {"name":"Sony FE 200-600mm F5.6-6.3 G OSS","lens_type":"Zoom","mount":"Sony E","coverage":"FF","focal_min_mm":200,"focal_max_mm":600,"aperture_min":5.6,"aperture_max":6.3,"min_f_number":32,"diaphragm_blades":11,"filter_thread_mm":95,"elements_count":24,"groups_count":17,"min_focus_distance_mm":2400,"max_magnification":0.2,"focus_motor":"DDSSM","autofocus":true,"weather_sealed":true,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":2115,"length_mm":318,"diameter_mm":111.5,"ois":true,"price_chf":1899,"price_usd":1999,"price_eur":1949,"notes":"Long‑reach wildlife/sports zoom with internal zoom mechanism.","sources":["https://www.sony.com/electronics/camera-lenses/sel200600g","https://www.dpreview.com/reviews/sony-200-600mm-f5-6-6-3-g-oss-review","https://www.digitec.ch/en/s1/product/sony-fe-200-600mm-f56-63-g-oss-sony-e-cameras-lens-11553607"]},
  {"name":"Sony E 16-55mm F2.8 G","lens_type":"Zoom","mount":"Sony E","coverage":"APS-C","focal_min_mm":16,"focal_max_mm":55,"aperture_min":2.8,"aperture_max":2.8,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":67,"elements_count":17,"groups_count":12,"min_focus_distance_mm":330,"max_magnification":0.2,"focus_motor":"XD Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Thailand","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":494,"length_mm":100,"diameter_mm":73,"ois":false,"price_chf":1299,"price_usd":1399,"price_eur":1349,"notes":"APS‑C constant‑aperture pro zoom for Sony E cameras.","sources":["https://www.sony.com/electronics/camera-lenses/sel1655g","https://www.lenstip.com/579.1-Lens_review-Sony_E_16-55_mm_f_2.8_G_Introduction.html","https://www.foto-erhardt.de/objektive/sony/sony-e-16-55mm-f-2-8-g.html"]},
  {"name":"Panasonic Lumix S PRO 24-70mm F2.8","lens_type":"Zoom","mount":"L-Mount","coverage":"FF","focal_min_mm":24,"focal_max_mm":70,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":82,"elements_count":18,"groups_count":16,"min_focus_distance_mm":370,"max_magnification":0.25,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":935,"length_mm":140,"diameter_mm":90,"ois":false,"price_chf":2399,"price_usd":2199,"price_eur":2299,"notes":"Professional standard zoom for Leica/Panasonic/Sigma L‑Mount bodies.","sources":["https://www.panasonic.com/global/consumer/lumix/s-lens/s-pro-24-70mm-f2-8.html","https://www.lenstip.com/572.1-Lens_review-Panasonic_Lumix_S_PRO_24-70_mm_f_2.8_Introduction.html","https://www.foto-erhardt.de/objektive/panasonic/panasonic-lumix-s-pro-24-70mm-f2-8.html"]},
  {"name":"Sigma 85mm F1.4 DG DN Art (L‑Mount)","lens_type":"Prime","mount":"L-Mount","coverage":"FF","focal_min_mm":85,"focal_max_mm":85,"aperture_min":1.4,"aperture_max":16,"min_f_number":16,"diaphragm_blades":11,"filter_thread_mm":77,"elements_count":15,"groups_count":11,"min_focus_distance_mm":850,"max_magnification":0.12,"focus_motor":"Stepper Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":625,"length_mm":94,"diameter_mm":82.8,"ois":false,"price_chf":1149,"price_usd":1199,"price_eur":1149,"notes":"Fast portrait prime in Sigma’s Art series, designed for mirrorless.","sources":["https://www.sigma-global.com/en/lenses/a020_85_14/","https://www.dpreview.com/reviews/sigma-85mm-f1-4-dg-dn-art-review","https://www.digitec.ch/en/s1/product/sigma-85mm-f14-dg-dn-art-l-mount-cameras-lens-13619873"]},
  {"name":"Leica APO‑Summicron‑SL 35mm F2 ASPH","lens_type":"Prime","mount":"L-Mount","coverage":"FF","focal_min_mm":35,"focal_max_mm":35,"aperture_min":2.0,"aperture_max":22,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":67,"elements_count":13,"groups_count":10,"min_focus_distance_mm":270,"max_magnification":0.2,"focus_motor":"Stepping Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Germany","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":750,"length_mm":102,"diameter_mm":73,"ois":false,"price_chf":4890,"price_usd":4795,"price_eur":4790,"notes":"Apochromatic standard prime with exceptional optical correction.","sources":["https://leica-camera.com/en/int/photography/lenses/sl/apo-summicron-sl-35-f2-asph","https://www.photoreview.com.au/reviews/lenses/leica-apo-summicron-sl-35mm-f2-asph/","https://www.foto-erhardt.de/objektive/leica/leica-apo-summicron-sl-35mm-f-2-asph.html"]},
  {"name":"Panasonic Lumix S PRO 70-200mm F2.8 OIS","lens_type":"Zoom","mount":"L-Mount","coverage":"FF","focal_min_mm":70,"focal_max_mm":200,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":82,"elements_count":22,"groups_count":17,"min_focus_distance_mm":950,"max_magnification":0.21,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1570,"length_mm":208,"diameter_mm":94.4,"ois":true,"price_chf":2899,"price_usd":2599,"price_eur":2799,"notes":"Professional telephoto zoom with Dual I.S. compatibility.","sources":["https://www.panasonic.com/global/consumer/lumix/s-lens/s-pro-70-200mm-f2-8.html","https://www.dpreview.com/news/3615637286/panasonic-unveils-lumix-s-pro-70-200mm-f2-8-ois-and-16-35mm-f4-lenses","https://www.foto-erhardt.de/objektive/panasonic/panasonic-lumix-s-pro-70-200mm-f-2-8-oes.html"]},
  {"name":"Sigma 14-24mm F2.8 DG DN Art (L-Mount)","lens_type":"Zoom","mount":"L-Mount","coverage":"FF","focal_min_mm":14,"focal_max_mm":24,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":null,"elements_count":18,"groups_count":13,"min_focus_distance_mm":280,"max_magnification":0.14,"focus_motor":"Stepper Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":795,"length_mm":131,"diameter_mm":85,"ois":false,"price_chf":1379,"price_usd":1399,"price_eur":1349,"notes":"Ultra-wide constant‑aperture zoom for L-Mount mirrorless.","sources":["https://www.sigma-global.com/en/lenses/a019_14_24_28/","https://www.lenstip.com/583.1-Lens_review-Sigma_14-24_mm_f_2.8_DG_DN_Art_Introduction.html","https://www.digitec.ch/en/s1/product/sigma-14-24mm-f28-dg-dn-art-l-mount-cameras-lens-11231579"]},
  {"name":"Leica Vario-Elmarit-SL 24-90mm F2.8-4 ASPH","lens_type":"Zoom","mount":"L-Mount","coverage":"FF","focal_min_mm":24,"focal_max_mm":90,"aperture_min":2.8,"aperture_max":4.0,"min_f_number":22,"diaphragm_blades":11,"filter_thread_mm":82,"elements_count":18,"groups_count":15,"min_focus_distance_mm":300,"max_magnification":0.27,"focus_motor":"Stepping Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Germany","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1140,"length_mm":138,"diameter_mm":88,"ois":true,"price_chf":5540,"price_usd":5495,"price_eur":5490,"notes":"Leica's premium standard zoom for SL and L-Mount bodies.","sources":["https://leica-camera.com/en-int/photography/lenses/sl/vario-elmarit-sl-24-90-f28-4-asph","https://www.photoreview.com.au/reviews/lenses/leica-vario-elmarit-sl-24-90mm-f2-8-4-asph/","https://www.foto-erhardt.de/objektive/leica/leica-vario-elmarit-sl-24-90mm-f-2-8-4-asph.html"]},
  {"name":"Fujifilm XF 16-55mm F2.8 R LM WR","lens_type":"Zoom","mount":"Fujifilm X","coverage":"APS-C","focal_min_mm":16,"focal_max_mm":55,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":77,"elements_count":17,"groups_count":12,"min_focus_distance_mm":300,"max_magnification":0.16,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":655,"length_mm":106,"diameter_mm":83.3,"ois":false,"price_chf":1149,"price_usd":1199,"price_eur":1149,"notes":"Pro standard zoom for X‑series; weather sealed and constant f/2.8.","sources":["https://fujifilm-x.com/global/products/lenses/xf16-55mmf28-r-lm-wr/","https://www.lenstip.com/430.1-Lens_review-Fujifilm_Fujinon_XF_16-55_mm_f_2.8_R_LM_WR_Introduction.html","https://www.digitec.ch/en/s1/product/fujifilm-xf-16-55mm-f28-r-lm-wr-fujifilm-x-cameras-lens-3472151"]},
  {"name":"Fujifilm XF 50-140mm F2.8 R LM OIS WR","lens_type":"Zoom","mount":"Fujifilm X","coverage":"APS-C","focal_min_mm":50,"focal_max_mm":140,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":72,"elements_count":23,"groups_count":16,"min_focus_distance_mm":1000,"max_magnification":0.12,"focus_motor":"Triple Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":995,"length_mm":175.9,"diameter_mm":82.9,"ois":true,"price_chf":1399,"price_usd":1599,"price_eur":1449,"notes":"Pro telephoto zoom with strong OIS and weather sealing.","sources":["https://fujifilm-x.com/global/products/lenses/xf50-140mmf28-r-lm-ois-wr/","https://www.photoreview.com.au/reviews/lenses/fujifilm-fujinon-xf-50-140mm-f2-8-r-lm-ois-wr/","https://www.foto-erhardt.de/objektive/fujifilm/fujifilm-xf-50-140mm-f-2-8-r-lm-ois-wr.html"]},
  {"name":"Fujifilm XF 23mm F1.4 R LM WR","lens_type":"Prime","mount":"Fujifilm X","coverage":"APS-C","focal_min_mm":23,"focal_max_mm":23,"aperture_min":1.4,"aperture_max":16,"min_f_number":16,"diaphragm_blades":9,"filter_thread_mm":58,"elements_count":15,"groups_count":10,"min_focus_distance_mm":190,"max_magnification":0.2,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Philippines","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":375,"length_mm":77.8,"diameter_mm":67,"ois":false,"price_chf":949,"price_usd":999,"price_eur":999,"notes":"Updated fast 35mm‑equiv prime with WR and linear AF motor.","sources":["https://fujifilm-x.com/global/products/lenses/xf23mmf14-r-lm-wr/","https://www.dpreview.com/reviews/fujifilm-xf-23mm-f1-4-r-lm-wr-review","https://www.foto-erhardt.de/objektive/fujifilm/fujifilm-xf-23mm-f-1-4-r-lm-wr.html"]},
  {"name":"Fujifilm GF 45mm F2.8 R WR","lens_type":"Prime","mount":"Fujifilm G","coverage":"Medium Format","focal_min_mm":45,"focal_max_mm":45,"aperture_min":2.8,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":62,"elements_count":8,"groups_count":6,"min_focus_distance_mm":450,"max_magnification":0.14,"focus_motor":"Micromotor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":490,"length_mm":88,"diameter_mm":84,"ois":false,"price_chf":1799,"price_usd":1699,"price_eur":1749,"notes":"Standard wide prime for GFX medium format; weather-sealed.","sources":["https://fujifilm-x.com/global/products/lenses/gf45mmf28-r-wr/","https://www.photoreview.com.au/reviews/lenses/fujifilm-gf-45mm-f2-8-r-wr/","https://www.foto-erhardt.de/objektive/fujifilm/fujifilm-gf-45mm-f-2-8-r-wr.html"]},
  {"name":"Fujifilm GF 100-200mm F5.6 R LM OIS WR","lens_type":"Zoom","mount":"Fujifilm G","coverage":"Medium Format","focal_min_mm":100,"focal_max_mm":200,"aperture_min":5.6,"aperture_max":32,"min_f_number":32,"diaphragm_blades":9,"filter_thread_mm":67,"elements_count":20,"groups_count":13,"min_focus_distance_mm":600,"max_magnification":0.2,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1050,"length_mm":183,"diameter_mm":89.5,"ois":true,"price_chf":1999,"price_usd":1999,"price_eur":2049,"notes":"Telephoto zoom for GFX; compatible with 1.4× teleconverter.","sources":["https://fujifilm-x.com/global/products/lenses/gf100-200mmf56-r-lm-ois-wr/","https://www.dpreview.com/reviews/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-sample-images","https://www.digitec.ch/en/s1/product/fujifilm-gf-100-200mm-f56-r-lm-ois-wr-fujifilm-g-cameras-lens-10662589"]},
  {"name":"Fujifilm XF 8-16mm F2.8 R LM WR","lens_type":"Zoom","mount":"Fujifilm X","coverage":"APS-C","focal_min_mm":8,"focal_max_mm":16,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":null,"elements_count":20,"groups_count":13,"min_focus_distance_mm":250,"max_magnification":0.1,"focus_motor":"Linear Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":805,"length_mm":121.5,"diameter_mm":88,"ois":false,"price_chf":1999,"price_usd":1999,"price_eur":1899,"notes":"Ultra‑wide constant‑aperture zoom for X‑Series; weather‑sealed.","sources":["https://fujifilm-x.com/global/products/lenses/xf8-16mmf28-r-lm-wr/","https://www.lenstip.com/555.1-Lens_review-Fujifilm_Fujinon_XF_8-16_mm_f_2.8_R_LM_WR_Introduction.html","https://www.foto-erhardt.de/objektive/fujifilm/fujifilm-xf-8-16mm-f-2-8-r-lm-wr.html"]},
  {"name":"OM System M.Zuiko Digital ED 12-40mm F2.8 PRO II","lens_type":"Zoom","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":12,"focal_max_mm":40,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":62,"elements_count":14,"groups_count":9,"min_focus_distance_mm":200,"max_magnification":0.3,"focus_motor":"MSC","autofocus":true,"weather_sealed":true,"country_of_origin":"Vietnam","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":382,"length_mm":84,"diameter_mm":69.9,"ois":false,"price_chf":999,"price_usd":999,"price_eur":999,"notes":"Updated PRO standard zoom with sealing improvements and fluorine coating.","sources":["https://omsystem.com/en/lenses/m-zuiko-digital-ed-12-40mm-f28-pro-ii-114/","https://www.photoreview.com.au/reviews/lenses/om-system-m-zuiko-digital-ed-12-40mm-f2-8-pro-ii/","https://www.digitec.ch/en/s1/product/olympus-mzuiko-digital-ed-12-40mm-f28-pro-ii-micro-four-thirds-cameras-lens-19488476"]},
  {"name":"OM System M.Zuiko Digital ED 40-150mm F2.8 PRO","lens_type":"Zoom","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":40,"focal_max_mm":150,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":72,"elements_count":16,"groups_count":10,"min_focus_distance_mm":700,"max_magnification":0.21,"focus_motor":"MSC","autofocus":true,"weather_sealed":true,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":760,"length_mm":160,"diameter_mm":79.4,"ois":false,"price_chf":1399,"price_usd":1499,"price_eur":1449,"notes":"Pro telephoto zoom for MFT with constant f/2.8 aperture.","sources":["https://omsystem.com/en/lenses/m-zuiko-digital-ed-40-150mm-f28-pro-70/","https://www.lenstip.com/423.1-Lens_review-Olympus_M_Zuiko_Digital_40-150_mm_f_2.8_PRO_Introduction.html","https://www.foto-erhardt.de/objektive/olympus/olympus-m-zuiko-digital-ed-40-150mm-f-2-8-pro.html"]},
  {"name":"Panasonic Leica DG Vario-Elmarit 8-18mm F2.8-4.0 ASPH","lens_type":"Zoom","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":8,"focal_max_mm":18,"aperture_min":2.8,"aperture_max":4.0,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":67,"elements_count":15,"groups_count":10,"min_focus_distance_mm":230,"max_magnification":0.12,"focus_motor":"Stepping Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":315,"length_mm":88,"diameter_mm":73.4,"ois":false,"price_chf":1149,"price_usd":1099,"price_eur":1149,"notes":"Ultra-wide versatile zoom made in collaboration with Leica.","sources":["https://www.panasonic.com/global/consumer/lumix/lenz/h-e08018.html","https://www.lenstip.com/511.1-Lens_review-Leica_DG_Vario-Elmarit_8-18_mm_f_2.8-4_ASPH._Introduction.html","https://www.foto-erhardt.de/objektive/panasonic/panasonic-leica-dg-vario-elmarit-8-18mm-f-2-8-4-0-asph.html"]},
  {"name":"OM System M.Zuiko Digital ED 17mm F1.2 PRO","lens_type":"Prime","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":17,"focal_max_mm":17,"aperture_min":1.2,"aperture_max":16,"min_f_number":16,"diaphragm_blades":9,"filter_thread_mm":62,"elements_count":15,"groups_count":11,"min_focus_distance_mm":200,"max_magnification":0.15,"focus_motor":"MSC","autofocus":true,"weather_sealed":true,"country_of_origin":"Vietnam","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":390,"length_mm":87,"diameter_mm":68.2,"ois":false,"price_chf":1379,"price_usd":1399,"price_eur":1349,"notes":"Pro portrait‑wide prime with weather sealing and beautiful bokeh.","sources":["https://omsystem.com/en/lenses/m-zuiko-digital-ed-17mm-f12-pro-54/","https://www.lenstip.com/526.1-Lens_review-Olympus_M_Zuiko_Digital_17_mm_f_1.2_PRO_Introduction.html","https://www.foto-erhardt.de/objektive/olympus/olympus-m-zuiko-digital-ed-17mm-f-1-2-pro.html"]},
  {"name":"OM System M.Zuiko Digital ED 300mm F4 IS PRO","lens_type":"Prime","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":300,"focal_max_mm":300,"aperture_min":4.0,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":77,"elements_count":17,"groups_count":10,"min_focus_distance_mm":1400,"max_magnification":0.24,"focus_motor":"MSC","autofocus":true,"weather_sealed":true,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":1270,"length_mm":227,"diameter_mm":92.5,"ois":true,"price_chf":2649,"price_usd":2499,"price_eur":2599,"notes":"Super telephoto prime with IS Sync support and weather sealing.","sources":["https://omsystem.com/en/lenses/m-zuiko-digital-ed-300mm-f4-is-pro-65/","https://www.dpreview.com/reviews/olympus-300mm-f4-pro-review","https://www.digitec.ch/en/s1/product/olympus-mzuiko-digital-ed-300mm-f4-is-pro-micro-four-thirds-cameras-lens-5629639"]},
  {"name":"Panasonic Leica DG Nocticron 42.5mm F1.2 ASPH Power OIS","lens_type":"Prime","mount":"Micro Four Thirds","coverage":"MFT","focal_min_mm":42.5,"focal_max_mm":42.5,"aperture_min":1.2,"aperture_max":16,"min_f_number":16,"diaphragm_blades":9,"filter_thread_mm":67,"elements_count":14,"groups_count":11,"min_focus_distance_mm":500,"max_magnification":0.1,"focus_motor":"Stepping Motor","autofocus":true,"weather_sealed":false,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":425,"length_mm":76.8,"diameter_mm":74,"ois":true,"price_chf":1499,"price_usd":1399,"price_eur":1449,"notes":"Premium Leica‑branded portrait prime with optical stabilization.","sources":["https://www.panasonic.com/global/consumer/lumix/lenz/h-hs043.html","https://www.lenstip.com/414.1-Lens_review-Panasonic_Leica_DG_Nocticron_42.5_mm_f_1.2_ASPH_Power_OIS_Introduction.html","https://www.foto-erhardt.de/objektive/panasonic/panasonic-leica-dg-nocticron-42-5mm-f-1-2-asph-power-ois.html"]},
  {"name":"Sigma 28-70mm F2.8 DG DN Contemporary (Sony E / L-Mount)","lens_type":"Zoom","mount":["Sony E","L-Mount"],"coverage":"FF","focal_min_mm":28,"focal_max_mm":70,"aperture_min":2.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":67,"elements_count":16,"groups_count":12,"min_focus_distance_mm":190,"max_magnification":0.34,"focus_motor":"Stepper Motor","autofocus":true,"weather_sealed":true,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":470,"length_mm":101.5,"diameter_mm":72.2,"ois":false,"price_chf":879,"price_usd":899,"price_eur":849,"notes":"Compact constant‑aperture standard zoom for mirrorless.","sources":["https://www.sigma-global.com/en/lenses/c021_28_70_28/","https://www.dpreview.com/reviews/sigma-28-70mm-f2-8-dg-dn-contemporary-review","https://www.digitec.ch/en/s1/product/sigma-28-70mm-f28-dg-dn-contemporary-sony-e-cameras-lens-14802339"]},
  {"name":"Tamron 28-200mm F2.8-5.6 Di III RXD (Sony E)","lens_type":"Zoom","mount":["Sony E"],"coverage":"FF","focal_min_mm":28,"focal_max_mm":200,"aperture_min":2.8,"aperture_max":5.6,"min_f_number":22,"diaphragm_blades":7,"filter_thread_mm":67,"elements_count":18,"groups_count":14,"min_focus_distance_mm":190,"max_magnification":0.32,"focus_motor":"RXD","autofocus":true,"weather_sealed":true,"country_of_origin":"Vietnam","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":575,"length_mm":117,"diameter_mm":74,"ois":false,"price_chf":849,"price_usd":729,"price_eur":799,"notes":"Travel superzoom with unusually bright f/2.8 wide end.","sources":["https://www.tamron.eu/lenses/28-200mm-f28-56-di-iii-rxd-a071/","https://www.dpreview.com/reviews/tamron-28-200mm-f2-8-5-6-di-iii-rxd-review","https://www.foto-erhardt.de/objektive/tamron/tamron-28-200mm-f-2-8-5-6-di-iii-rxd-sony-e.html"]},
  {"name":"Samyang AF 35mm F1.8 FE","lens_type":"Prime","mount":["Sony E"],"coverage":"FF","focal_min_mm":35,"focal_max_mm":35,"aperture_min":1.8,"aperture_max":22,"min_f_number":22,"diaphragm_blades":9,"filter_thread_mm":58,"elements_count":10,"groups_count":8,"min_focus_distance_mm":290,"max_magnification":0.17,"focus_motor":"Linear STM","autofocus":true,"weather_sealed":true,"country_of_origin":"Korea","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":210,"length_mm":63.5,"diameter_mm":65,"ois":false,"price_chf":399,"price_usd":399,"price_eur":379,"notes":"Compact AF prime lens for Sony full‑frame.","sources":["https://www.samyanglens.com/en/product/product-view.php?seq=450","https://www.photoreview.com.au/reviews/lenses/samyang-af-35mm-f1-8-fe/","https://www.foto-erhardt.de/objektive/samyang/samyang-af-35mm-f-1-8-fe.html"]},
  {"name":"Laowa 15mm F4.5 Zero-D Shift","lens_type":"Prime","mount":["Canon RF","Nikon Z","Sony E","L-Mount","Canon EF","Nikon F"],"coverage":"FF","focal_min_mm":15,"focal_max_mm":15,"aperture_min":4.5},
  {"diaphragm_blades":5,"filter_thread_mm":null,"elements_count":17,"groups_count":11,"min_focus_distance_mm":200,"max_magnification":0.2,"focus_motor":"Manual Focus","autofocus":false,"weather_sealed":false,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":747,"length_mm":103,"diameter_mm":79,"ois":false,"price_chf":1299,"price_usd":1199,"price_eur":1249,"notes":"Ultra‑wide shift lens with minimal distortion, ideal for architecture.","sources":["https://www.venuslens.net/product/laowa-15mm-f4-5-zero-d-shift/","https://www.dpreview.com/news/6727391217/laowa-announces-15mm-f4-5-zero-d-shift-lens-for-full-frame-cameras","https://www.foto-erhardt.de/objektive/laowa/laowa-15mm-f-4-5-zero-d-shift.html"]},
  {"name":"Voigtländer Nokton 50mm F1.0 Aspherical (Nikon Z)","lens_type":"Prime","mount":["Nikon Z"],"coverage":"FF","focal_min_mm":50,"focal_max_mm":50,"aperture_min":1.0,"aperture_max":16,"min_f_number":16,"diaphragm_blades":12,"filter_thread_mm":67,"elements_count":9,"groups_count":7,"min_focus_distance_mm":450,"max_magnification":0.15,"focus_motor":"Manual Focus","autofocus":false,"weather_sealed":false,"country_of_origin":"Japan","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":598,"length_mm":89.5,"diameter_mm":76.8,"ois":false,"price_chf":1799,"price_usd":1599,"price_eur":1699,"notes":"Ultra‑fast manual‑focus normal lens with classic rendering and extreme bokeh.","sources":["https://www.cosina.co.jp/voigtlander/en/nokton-50mm-f1-aspherical-z/","https://www.dpreview.com/news/5514188665/voigtlander-releases-nokton-50mm-f1-0-aspherical-lens-for-nikon-z-mount","https://www.digitec.ch/en/s1/product/voigtlander-nokton-50mm-f10-asph-nikon-z-cameras-lens-21750177"]},
  {"name":"TTArtisan 11mm F2.8 Fisheye","lens_type":"Prime","mount":["Sony E","Nikon Z","Canon RF","L-Mount","Fuji X","Canon EF","Nikon F"],"coverage":"FF","focal_min_mm":11,"focal_max_mm":11,"aperture_min":2.8,"aperture_max":16,"min_f_number":16,"diaphragm_blades":7,"filter_thread_mm":null,"elements_count":11,"groups_count":7,"min_focus_distance_mm":170,"max_magnification":null,"focus_motor":"Manual Focus","autofocus":false,"weather_sealed":false,"country_of_origin":"China","sustainability":{"re100":null,"sbti":null,"co2_kg":null,"climate_contribution_chf":null},"weight_g":485,"length_mm":90,"diameter_mm":82,"ois":false,"price_chf":249,"price_usd":199,"price_eur":229,"notes":"Budget full‑frame fisheye with 180° angle of view.","sources":["https://ttartisan.com/product/11mm-f2-8-fisheye/","https://www.photoreview.com.au/reviews/lenses/ttartisan-11mm-f2-8-fisheye/","https://www.digitec.ch/en/s1/product/ttartisan-11mm-f28-fisheye-sony-e-cameras-lens-15581598"]}
];

const brandFromName = (name) => {
  const brandCandidates = [
    'Canon', 'Nikon', 'Sony', 'Panasonic', 'Sigma', 'Leica', 'Fujifilm', 'OM System',
    'Tamron', 'Samyang', 'Laowa', 'Voigtländer', 'TTArtisan'
  ];
  const hit = brandCandidates.find(b => name.startsWith(b + ' '));
  if (hit) return hit;
  // Panasonic Leica -> Panasonic
  if (name.startsWith('Panasonic Leica')) return 'Panasonic';
  return name.split(' ')[0];
};

const mapMountShort = (m) => {
  const s = (m || '').toString();
  if (/Canon RF/i.test(s)) return 'RF';
  if (/Canon EF/i.test(s)) return 'EF';
  if (/Nikon Z/i.test(s)) return 'Z';
  if (/Nikon F/i.test(s)) return 'F';
  if (/Sony E/i.test(s)) return 'E';
  if (/L-?Mount/i.test(s)) return 'L';
  if (/Fujifilm X/i.test(s) || /Fuji X/i.test(s)) return 'X';
  if (/Fujifilm G/i.test(s)) return 'G';
  if (/Micro Four Thirds/i.test(s) || /MFT/i.test(s)) return 'MFT';
  return s;
};

const isZoom = (l) => (l.focal_min_mm ?? 0) !== (l.focal_max_mm ?? 0);

const inferDistortion = (l) => {
  if (/Fisheye/i.test(l.name)) return 6.0;
  const minF = l.focal_min_mm || l.focal_max_mm || 35;
  if (minF <= 20) return 2.5;
  if (isZoom(l)) return 2.0;
  return 0.5;
};

const inferBreathing = (l) => {
  if (/(GM|S\b|PRO\b|APO)/i.test(l.name)) return 9;
  return 7;
};

const inferIsMacro = (l) => {
  const mm = l.max_magnification;
  if (typeof mm === 'number' && mm >= 1.0) return true;
  return /macro/i.test(l.name);
};

function explodeMountsAndNormalize(entry) {
  const mounts = Array.isArray(entry.mount) ? entry.mount : [entry.mount];
  const srcUrl = Array.isArray(entry.sources) && entry.sources.length > 0 ? entry.sources[0] : '';
  return mounts.map((m) => {
    const mountShort = mapMountShort(m);
    return {
      name: entry.name,
      brand: brandFromName(entry.name),
      mount: mountShort,
      coverage: entry.coverage || 'FF',
      focal_min_mm: entry.focal_min_mm,
      focal_max_mm: entry.focal_max_mm,
      aperture_min: entry.aperture_min,
      aperture_max: entry.aperture_max,
      weight_g: entry.weight_g,
      ois: Boolean(entry.ois),
      price_chf: entry.price_chf,
      weather_sealed: Boolean(entry.weather_sealed),
      is_macro: inferIsMacro(entry),
      distortion_pct: inferDistortion(entry),
      focus_breathing_score: inferBreathing(entry),
      source_url: srcUrl
    };
  });
}

function normalizeAll(entries) {
  const out = [];
  for (const e of entries) {
    // Some rows were broken across objects; merge consecutive partial objects
    if (!e.name && out.length > 0) {
      Object.assign(out[out.length - 1], e);
      continue;
    }
    out.push(e);
  }
  return out.flatMap(explodeMountsAndNormalize);
}

function dedupeMerge(existing, incoming) {
  const byKey = new Map();
  for (const l of existing) {
    byKey.set(`${l.name}__${l.mount}`, l);
  }
  for (const l of incoming) {
    byKey.set(`${l.name}__${l.mount}`, l);
  }
  return Array.from(byKey.values())
    .filter(l => l && l.name && l.mount)
    .sort((a, b) => a.name.localeCompare(b.name) || a.mount.localeCompare(b.mount));
}

function readJson(fp) {
  return JSON.parse(fs.readFileSync(fp, 'utf-8'));
}
function writeJson(fp, data) {
  fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n', 'utf-8');
}

function run() {
  const serverLensPath = path.join(ROOT, 'server', 'data', 'lenses.json');
  const publicLensPath = path.join(ROOT, 'data', 'lenses.json');
  const existingServer = readJson(serverLensPath);
  const existingPublic = readJson(publicLensPath);
  const normalized = normalizeAll(provided);
  const merged = dedupeMerge(existingServer, normalized);
  writeJson(serverLensPath, merged);
  // Keep public lenses identical
  writeJson(publicLensPath, merged);
  console.log(`Updated ${serverLensPath} and ${publicLensPath} with ${merged.length} lenses.`);
}

run();


