name: e2e

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root deps
        run: HUSKY=0 npm ci

      - name: Install client deps
        run: HUSKY=0 npm --workspace client ci

      - name: Install server deps
        run: HUSKY=0 npm --workspace server ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        env:
          NODE_ENV: development
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          if-no-files-found: ignore


